### PR TITLE
Upgrade to v5.20.4

### PR DESCRIPTION
**Pull request by hexchain**
There are a lot of questionable hacks here, but it should work.

### CODE REVIEW

**Comment by soredake** [comment]
Any progress on this?

**Comment by barthalion** [comment]
cc @flathub/kde

**Comment by tsdgeos** [comment]
I didnt't even know this was under our merge approval area, i mean it's org.gtk ;)

About the MR It deletes json and converts to yaml for no appearent reason, so under org.kde.* that'd be a direct no from me.

Also update to 5.20.4 while at it i guess?

**Comment by hexchain** [comment]
The reason is that there are some hacks (not using CMake and moving assets) and I want it documented, so I want YAML for the comment syntax. I'll revert if you don't like them.

**Comment by tsdgeos** [comment]
As said, i don't really *feel* responsible for this, even i have the green button to Merge enabled so i guess i kind of am :+1: 

Update to the new runtime? or needs to be on the old for some gtk reason?

**Comment by barthalion** [comment]
@tsdgeos It was submitted and maintained by @aleixpol and given it's technically KDE project, I quickly added it to KDE team.

**Comment by hexchain** [comment]
I didn't (or forgot to) touch that. But is there any compatibility implications? If I update the runtime version to 20.08, does it become incompatible with 19.08? I didn't see a clear pattern from other theme packages.

**Comment by tsdgeos** [comment]
> @tsdgeos It was submitted and maintained by @aleixpol and given it's technically KDE project, I quickly added it to KDE team.

Fair enough, i would expect it to be called org.kde.Gtk3theme.Breeze though, i mean afaiu the reverse naming thing is "where does this come from", but that's details :)

**Comment by tsdgeos** [comment]
> I didn't (or forgot to) touch that. But is there any compatibility implications? If I update the runtime version to 20.08, does it become incompatible with 19.08? I didn't see a clear pattern from other theme packages.

Not a flatpak+gtk theme expert, I'd say yes, but i'd say it's also true the other way around and given 20.08 is "the way to go" unless you can find all the rest of gtk themes are on 19.08 i'd prefer to use 20.08

**Comment by hexchain** [comment]
Updated the runtime version, converted back to JSON, and squashed the commits.

**Comment by Erick555** [comment]
> Fair enough, i would expect it to be called org.kde.Gtk3theme.Breeze though, i mean afaiu the reverse naming thing is "where does this come from", but that's details :)

No, all gtk theme extensions must be named as [org.gtk.Gtk3theme.xxx](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/flatpak-images/platform.bst#L56) otherwise they won't work.

> Not a flatpak+gtk theme expert, I'd say yes, but i'd say it's also true the other way around and given 20.08 is "the way to go" unless you can find all the rest of gtk themes are on 19.08 i'd prefer to use 20.08

After a brief look I couldn't find gtk theme that is build against 20.08 and most doesn't even use 19.08 however as long as they don't provide any binaries it shouldn't matter for compatibility. If they did then due to glibc backward compatibility and forward incompatibility they should be build against the oldest supported runtime but that's not relevant for them.

**Comment by hexchain** [comment]
Friendly ping.

**Comment by tsdgeos** [comment]
> No, all gtk theme extensions must be named as org.gtk.Gtk3theme.xxx otherwise they won't work.

That's a bad design choice if you ask me

**Comment by tsdgeos** [comment]
> Friendly ping.

I am going to personally abstrain from this, i don't use any gtk app in flatpak so i can't test it

@barthalion says it was submitted by Aleix but all i can see in https://github.com/flathub/org.gtk.Gtk3theme.Breeze/commits/master is @TingPing and @bilelmoussaoui maybe I am looking at it wrong.

**Pull request merged**
